version: "2"

services:
  portainer:
    networks:
      traefik:
      management:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.entrypoints=web-secure"
      - "traefik.http.routers.portainer.rule=Host(`portainer.${FQDN:?err}`)"
      - "traefik.http.routers.portainer.middlewares=ip-in-whitelist"
      - "traefik.http.routers.portainer.tls=true"
      - "traefik.http.routers.portainer.service=portainer"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"
  vaultwarden:
    networks:
      traefik:
      management:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.vaultwarden.entrypoints=web-secure"
      - "traefik.http.routers.vaultwarden.rule=Host(`vault.${FQDN:?err}`)"
      - "traefik.http.routers.vaultwarden.tls=true"
      - "traefik.http.routers.vaultwarden.service=vaultwarden"
      - "traefik.http.services.vaultwarden.loadbalancer.server.port=80"
  watchtower:
    networks:
      management:

networks:
  traefik:
    external: true
    name: traefik
  management:
    name: management
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.20.3.0/24
        gateway: 172.20.3.1