version: '3.9'

services:
  portainer:
    image: portainer/portainer-ce:${PORTAINERTAG:-latest}
    container_name: portainer
    hostname: portainer
    expose:
      - 9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "portainer-data:/data"
    restart: unless-stopped

volumes:
  portainer-data: