version: "3.9"

services:
  vaultwarden:
    image: vaultwarden/server:${VAULTWARDENTAG:-latest}
    container_name: vaultwarden
    hostname: vaultwarden
    profiles:
      - vaultwarden
    expose:
      - 80
    environment:
            ADMIN_TOKEN: ${VAULTWARDENPASS:-vaultwardentoken}
    volumes:
      - "vaultwarden-data:/data"
    restart: unless-stopped

volumes:
  vaultwarden-data:
