api:
  dashboard: true
  debug: true
entryPoints:
  web:
    address: ":80"
  web-secure:
    address: ":443"
serversTransport:
  insecureSkipVerify: true
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: traefik
  file:
    filename: /traefik.yaml
certificatesResolvers:
  duckdns:
    acme:
      caServer: https://acme-staging-v02.api.letsencrypt.org/directory
      email: test@gmail.com
      storage: letsencrypt/acme.json
      dnsChallenge:
        provider: duckdns
        resolvers:
          - "1.1.1.1:53"
          - "1.0.0.1:53"
  
http:
  middlewares:
    redirect-to-https:
      redirectScheme:
        scheme: https
  routers:
    redirect-to-https:
      entrypoints:
        - web
      middlewares:
        - redirect-to-https
      rule: "HostRegexp(`{host:.+}`)"
      service: noop@internal