version: "2"

services:
  mongodb:
    networks:
      databases:
    ports:
      - 27017:27017
  mongo-express:
    networks:
      traefik:
      databases:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mongo-express.entrypoints=web-secure"
      - "traefik.http.routers.mongo-express.rule=Host(`mongo.${FQDN:?err}`)"
      - "traefik.http.routers.mongo-express.middlewares=ip-in-whitelist"
      - "traefik.http.routers.mongo-express.tls=true"
      - "traefik.http.routers.mongo-express.service=mongo-express"
      - "traefik.http.services.mongo-express.loadbalancer.server.port=8081"

networks:
  traefik:
    external: true
    name: traefik
  databases:
    name: databases
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.20.4.0/24
        gateway: 172.20.4.1