version: "2"

services:
  mongodb:
    image: mongo:${MONGOTAG:-latest}
    hostname: mongodb
    container_name: mongodb
    expose:
      - 27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: &mongorootuser ${MONGOROOTUSER:-root}
      MONGO_INITDB_ROOT_PASSWORD: &mongorootpass ${MONGOROOTPASS:-mongorootpass}
    restart: unless-stopped

  mongo-express:
    image: mongo-express:${MONGOEXPRESSTAG:-latest}
    hostname: mongo-express
    container_name: mongo-express
    expose:
      - 8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      ME_CONFIG_MONGODB_ADMINUSERNAME: *mongorootuser
      ME_CONFIG_MONGODB_ADMINPASSWORD: *mongorootpass
      ME_CONFIG_BASICAUTH_USERNAME: *mongorootuser
      ME_CONFIG_BASICAUTH_PASSWORD: *mongorootpass
    restart: unless-stopped