version: "2"

services:

  pihole:
    networks:
      networking:
        ipv4_address: ${PIHOLENETIP}
      traefik:
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pihole.rule=Host(`pihole.${FQDN:?err}`)"
      - "traefik.http.services.pihole.loadbalancer.server.port=80"
      - "traefik.docker.network=traefik"

  traefik:
    networks:
      networking:
        ipv4_address: ${TRAEFIKNETIP}
      traefik:
    ports:
      - 80:80
      - 443:443
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.middlewares.traefik-auth.basicauth.users=${TRAEFIKUSERPASS}"
      - "traefik.http.routers.traefik.rule=Host(`traefik.${FQDN:?err}`)"
      - "traefik.http.routers.traefik.service=api@internal"
      #HTTPS
      - "traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.routers.traefik.middlewares=traefik-https-redirect"
      - "traefik.http.routers.traefik-secure.entrypoints=https"
      - "traefik.http.routers.traefik-secure.rule=Host(`traefik.${FQDN:?err}`)"
      - "traefik.http.routers.traefik-secure.middlewares=traefik-auth"
      - "traefik.http.routers.traefik-secure.tls=true"
      - "traefik.http.routers.traefik-secure.tls.certresolver=duckdns"
      - "traefik.http.routers.traefik-secure.tls.domains[0].main=${FQDN:?err}"
      - "traefik.http.routers.traefik-secure.tls.domains[0].sans=*.${FQDN:?err}"
      - "traefik.http.routers.traefik-secure.service=api@internal"

  wireguard:
    networks:
      networking:
        ipv4_address: ${WGNETIP}
      traefik:
    ports:
      - 51820:51820
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wireguard.rule=Host(`wireguard.${FQDN:?err}`)"
      - "traefik.http.services.wireguard.loadbalancer.server.port=51821"
      - "traefik.docker.network=traefik"
  
networks:
  networking:
    name: networking
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.20.1.0/24
        gateway: 172.20.1.1
  traefik:
    name: traefik
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.20.2.0/24
        gateway: 172.20.2.1