version: "3.9"

services:
  traefik:
    image: "traefik"
    container_name: "traefik"
    profiles:
      - traefik
    environment:
      DUCKDNS_TOKEN: ${DUCKDNSTOKEN:?err}
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik/traefik-conf.yaml:/traefik.yaml"
      - traefik-cert:/letsencrypt
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped

volumes:
  traefik-cert: