---
enableTraefik: &traefik True
enableUIDGID: False

# All files used except docker-compose.* files
stacks:
  databases:
    files:
      - mongo.yaml
    profiles:
      mongo: true
  file-sharing:
    files:
      - filebrowser.yaml
      - filezilla.yaml
    profiles:
      filebrowser: true
      filezilla: false
  management:
    files:
      - portainer.yaml
      - vaultwarden.yml
      - watchtower.yaml
    profiles: 
      portainer: true
      vaultwarden: false
      watchtower: true
  networking:
    files:
      - pihole.yaml
      - traefik.yaml
      - wireguard.yaml
    profiles:
      traefik: *traefik
      pihole: true
      wireguard: true
      
    
