name: Stack Deployer
on:
  push:
    branches:
      - 'main'

jobs:
  deploy_docker_stacks:
    runs-on: self-hosted
    env:
      COMPOSE_CMD: docker-compose up -d
    steps:
      - name: Pull last commit on main
        uses: actions/checkout@main
      - name: Expand sensitive data
        run: |
          sed 's@\$FQDN@'"${{ secrets.FQDN }}"'@'
          sed 's@\$DUCKDNSTOKE@'"${{ secrets.DUCKDNSTOKEN }}"'@'
          sed 's@\$ALLPASS@'"${{ secrets.ALLPASS }}"'@'
        
      - name: Generate YAML with envireonment variables from secret
        run: echo $ENV_VARS_YAML > envvars.yaml
        env:
          ENV_VARS_YAML: ${{ secrets.ENV_VARS_YAML }}
        working-directory: pyconfig.d
      - name: Generate environment files from 
        run: python3 create_env_files.py
        env:
          ALLPASS: ${{ secrets.ALLPASS }}
          FQDN: ${{ secrets.FQDN }}
          DUCKDNSTOKEN: ${{ secrets.DUCKDNSTOKEN }}
      - name: Deploy Networking stack
        working-directory: networking
        run: $COMPOSE_CMD
      - name: Deploy Management stack
        working-directory: management
        run: $COMPOSE_CMD
      - name: Deploy File Sharing stack
        working-directory: management
        run: $COMPOSE_CMD
