name: Stack Deployer
on:
  push:
    branches:
      - 'main'

jobs:
  deploy_docker_stacks:
    runs-on: self-hosted
    env:
      COMPOSE_CMD: docker-compose up -d
    steps:
      - name: Pull last commit on main
        uses: actions/checkout@main
      - name: Expand sensitive data
        working-directory: pyconfig.d
        run: |
          sed -i 's/\$FQDN/${{ secrets.FQDN }}/g' envvars.yaml
          sed -i 's/\$DUCKDNSTOKEN/${{ secrets.DUCKDNSTOKEN }}/g' envvars.yaml
          sed -i 's/\$ALLPASS/${{ secrets.ALLPASS }}/g' envvars.yaml
      - name: Generate environment files from 
        run: python3 create_env_files.py
        env:
          ALLPASS: ${{ secrets.ALLPASS }}
          FQDN: ${{ secrets.FQDN }}
          DUCKDNSTOKEN: ${{ secrets.DUCKDNSTOKEN }}
      - name: Deploy Networking stack
        working-directory: networking
        run: $COMPOSE_CMD
      - name: Deploy Management stack
        working-directory: management
        run: $COMPOSE_CMD
      - name: Deploy File Sharing stack
        working-directory: management
        run: $COMPOSE_CMD
